# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Authentication.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QStatusBar


class Ui_Authentication(object):
    def setupUi(self, Authentication):
        Authentication.setObjectName("Authentication")
        Authentication.resize(800, 400)
        Authentication.setMinimumSize(QtCore.QSize(400, 200))
        self.centralwidget = QtWidgets.QWidget(Authentication)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 90, 251, 42))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 140, 251, 42))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 90, 158, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 111, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 37, 571, 41))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 240, 201, 44))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 110, 127, 44))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 240, 221, 44))
        self.pushButton_3.setObjectName("pushButton_3")
        Authentication.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Authentication)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 42))
        self.menubar.setObjectName("menubar")
        Authentication.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Authentication)
        self.statusbar.setObjectName("statusbar")
        Authentication.setStatusBar(self.statusbar)

        self.status = QStatusBar(self.centralwidget)        
        self.status.setGeometry(QtCore.QRect(10, 100, 100, 20))
        Authentication.setStatusBar(self.status)

        self.retranslateUi(Authentication)
        QtCore.QMetaObject.connectSlotsByName(Authentication)

    def retranslateUi(self, Authentication):
        _translate = QtCore.QCoreApplication.translate
        Authentication.setWindowTitle(_translate("Authentication", "Authentication"))
        self.label.setText(_translate("Authentication", "Username/Login"))
        self.label_2.setText(_translate("Authentication", "Password"))
        self.label_3.setText(_translate("Authentication", "Enter the data for authentication in the system."))
        self.pushButton.setText(_translate("Authentication", "forgot the password"))
        self.pushButton_2.setText(_translate("Authentication", "Sign in "))
        self.pushButton_3.setText(_translate("Authentication", "create new account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Authentication = QtWidgets.QMainWindow()
    ui = Ui_Authentication()
    ui.setupUi(Authentication)
    Authentication.show()
    sys.exit(app.exec_())
