# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Create_new_account.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QStatusBar


class Ui_Create_new_account(object):
    def setupUi(self, Create_new_account):
        Create_new_account.setObjectName("Create_new_account")
        Create_new_account.resize(752, 400)
        self.centralwidget = QtWidgets.QWidget(Create_new_account)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(240, 90, 251, 42))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 111, 41))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 90, 158, 41))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 140, 251, 42))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 171, 41))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(240, 190, 251, 42))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 140, 251, 44))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 571, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 240, 171, 41))
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(240, 240, 251, 42))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(240, 290, 251, 42))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 290, 201, 41))
        self.label_6.setObjectName("label_6")
        Create_new_account.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Create_new_account)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 42))
        self.menubar.setObjectName("menubar")
        Create_new_account.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Create_new_account)
        self.statusbar.setObjectName("statusbar")
        Create_new_account.setStatusBar(self.statusbar)

        self.status = QStatusBar(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(20, 250, 100, 20))
        Create_new_account.setStatusBar(self.status)

        self.retranslateUi(Create_new_account)
        QtCore.QMetaObject.connectSlotsByName(Create_new_account)

    def retranslateUi(self, Create_new_account):
        _translate = QtCore.QCoreApplication.translate
        Create_new_account.setWindowTitle(_translate("Create_new_account", "Create_new_account"))
        self.label_2.setText(_translate("Create_new_account", "Passowrd"))
        self.label.setText(_translate("Create_new_account", "Name/Login"))
        self.label_3.setText(_translate("Create_new_account", "Repeat passowrd"))
        self.pushButton_3.setText(_translate("Create_new_account", "create new account"))
        self.label_4.setText(_translate("Create_new_account", "Enter the data for creating new account in the system."))
        self.label_5.setText(_translate("Create_new_account", "Secret question"))
        self.label_6.setText(_translate("Create_new_account", "Answer on question"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Create_new_account = QtWidgets.QMainWindow()
    ui = Ui_Create_new_account()
    ui.setupUi(Create_new_account)
    Create_new_account.show()
    sys.exit(app.exec_())
