# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Macchanger.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Macchanger(object):
    def setupUi(self, Macchanger):
        Macchanger.setObjectName("Macchanger")
        Macchanger.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Macchanger)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 170, 161, 44))
        self.pushButton.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 431, 31))
        self.label.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 161, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(180, 50, 291, 42))
        self.lineEdit.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 170, 161, 44))
        self.pushButton_2.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 230, 631, 271))
        self.listWidget.setStyleSheet("font: 20pt \"Noto Sans\";\n"
"font: 16pt \"Noto Sans\";")
        self.listWidget.setObjectName("listWidget")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 110, 181, 42))
        self.lineEdit_2.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 171, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 170, 161, 44))
        self.pushButton_3.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.pushButton_3.setObjectName("pushButton_3")
        Macchanger.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Macchanger)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 42))
        self.menubar.setObjectName("menubar")
        Macchanger.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Macchanger)
        self.statusbar.setObjectName("statusbar")
        Macchanger.setStatusBar(self.statusbar)

        self.retranslateUi(Macchanger)
        QtCore.QMetaObject.connectSlotsByName(Macchanger)

    def retranslateUi(self, Macchanger):
        _translate = QtCore.QCoreApplication.translate
        Macchanger.setWindowTitle(_translate("Macchanger", "MainWindow"))
        self.pushButton.setText(_translate("Macchanger", "Change MAC"))
        self.label.setText(_translate("Macchanger", "<html><head/><body><p><span style=\" font-size:12pt;\">This tool for the change you MAC address.</span></p></body></html>"))
        self.label_2.setText(_translate("Macchanger", "<html><head/><body><p><span style=\" font-size:16pt;\">Input new MAC:</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Macchanger", "Return Toolbar"))
        self.label_3.setText(_translate("Macchanger", "<html><head/><body><p><span style=\" font-size:16pt;\">Input interface:</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Macchanger", "Get current MAC"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Macchanger = QtWidgets.QMainWindow()
    ui = Ui_Macchanger()
    ui.setupUi(Macchanger)
    Macchanger.show()
    sys.exit(app.exec_())
