# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NetScanner.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NetworkScanner(object):
    def setupUi(self, NetworkScanner):
        NetworkScanner.setObjectName("NetworkScanner")
        NetworkScanner.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(NetworkScanner)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 120, 127, 44))
        self.pushButton_2.setObjectName("pushButton_2")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 180, 671, 331))
        self.listWidget.setObjectName("listWidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(180, 120, 211, 42))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 120, 161, 31))
        self.label.setObjectName("label")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 10, 341, 101))
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(460, 30, 161, 44))
        self.pushButton_3.setObjectName("pushButton_3")
        NetworkScanner.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NetworkScanner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 42))
        self.menubar.setObjectName("menubar")
        NetworkScanner.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NetworkScanner)
        self.statusbar.setObjectName("statusbar")
        NetworkScanner.setStatusBar(self.statusbar)

        self.retranslateUi(NetworkScanner)
        QtCore.QMetaObject.connectSlotsByName(NetworkScanner)

    def retranslateUi(self, NetworkScanner):
        _translate = QtCore.QCoreApplication.translate
        NetworkScanner.setWindowTitle(_translate("NetworkScanner", "NetworkScanner"))
        self.pushButton_2.setText(_translate("NetworkScanner", "Start scan"))
        self.label.setText(_translate("NetworkScanner", "Input IP-range"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("NetworkScanner", "Input IP-range for scan"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("NetworkScanner", "Example: 192.168.243.0/24"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.pushButton_3.setText(_translate("NetworkScanner", "Return Toolbar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NetworkScanner = QtWidgets.QMainWindow()
    ui = Ui_NetworkScanner()
    ui.setupUi(NetworkScanner)
    NetworkScanner.show()
    sys.exit(app.exec_())
