# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Toolbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Toolbar(object):
    def setupUi(self, Toolbar):
        Toolbar.setObjectName("Toolbar")
        Toolbar.resize(400, 800)
        Toolbar.setMinimumSize(QtCore.QSize(400, 800))
        self.centralwidget = QtWidgets.QWidget(Toolbar)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 20, 231, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        Toolbar.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Toolbar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 36))
        self.menubar.setObjectName("menubar")
        Toolbar.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Toolbar)
        self.statusbar.setObjectName("statusbar")
        Toolbar.setStatusBar(self.statusbar)

        self.retranslateUi(Toolbar)
        QtCore.QMetaObject.connectSlotsByName(Toolbar)

    def retranslateUi(self, Toolbar):
        _translate = QtCore.QCoreApplication.translate
        Toolbar.setWindowTitle(_translate("Toolbar", "MainWindow"))
        self.pushButton.setText(_translate("Toolbar", "Macchanger"))
        self.pushButton_2.setText(_translate("Toolbar", "IP info"))
        self.pushButton_3.setText(_translate("Toolbar", "Networkscanner"))
        self.pushButton_4.setText(_translate("Toolbar", "Profile"))
        self.pushButton_5.setText(_translate("Toolbar", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Toolbar = QtWidgets.QMainWindow()
    ui = Ui_Toolbar()
    ui.setupUi(Toolbar)
    Toolbar.show()
    sys.exit(app.exec_())
